version: '27.2.0'
services:
  rtmp-server:
    image: rtmp:v1
    container_name: rtmpC1
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '1935:1935'
      - '443:443'
    env_file:
      - .env.prod